Seance14
scarabe22/nfa085 pull request #10
Opened 2023-05-04 20:23 UTC by scarabe22

Voici ma proposition de séance 14

2023-05-05 00:24 UTC, jcheron commented
C'est partiel pour l'instant ?
C'est surtout la partie SPA qui me fait poser la question.

2023-05-05 11:40 UTC, scarabe22 commented
> C'est partiel pour l'instant ? C'est surtout la partie SPA qui me fait poser la question.

2023-05-05 11:44 UTC, scarabe22 commented
Compléments sur exo 2 spa

2023-05-05 23:26 UTC, jcheron requested changes
Les sujets ne sont pas évidents...
donc il faut apporter des corrections pour améliorer l'approche

2023-05-05 23:26 UTC, jcheron commented on Documents/seance14/acp.md
> +Il s'agit de préciser la nature unique d'un vin selon son millesime.
Le millésime, c'est l'année d'un vin...
Si on prend le millésime pour identifiant (année du vin) , on va se retrouver avec un identifiant qui ne sera pas unique, puisque vous aurez par exemple du Chateau-laffite 2023, et du chateau margaux 2023, soit autant de fois 2023 qu'il y aura de vins resencés en 2023.
Le millésime doit donc être identifié relativement au vin auquel il appartient :

![image](https://user-images.githubusercontent.com/2511052/236582127-95ab02c2-56f0-40dd-81c8-377ca1dc3e95.png)

Et en conséquence, **composer** n'est pas une ternaire, mais une bianaire entre Millésime et Cépage

2023-05-05 23:26 UTC, jcheron commented on Documents/seance14/acp.md
> +`status` correspond à SOS (boléen)
booléen

2023-05-05 23:26 UTC, jcheron commented on Documents/seance14/acp.md
> +Il s'agit de préciser la nature unique d'un vin selon son millesime.
Le `LotEnVente` ne concerne qu'un seul `Millésime`
Ce qui explique que la clé du Millésime : `idVin, millesime` ait migré dans le `LotEnVente`

2023-05-05 23:26 UTC, jcheron commented on Documents/seance14/acp.md
> +**Animal** = (<ins>idAnimal</ins>, dateEntree, espece, nom, sexe, complement, race, dateNaisance, numIdentification, description, compatibilite, #idEspece, #idStatusSos, #idRace, #idAdoptant, #idRefu
présence de `espece` et `#idEspece`...
Et si on a la race de l'animal, on connait son espece non ?

2023-05-05 23:26 UTC, jcheron commented on Documents/seance14/acp.md
> +**Tarif** = (<ins>idTarif</ins>, montant)
Si on connait l'espèce, on connait le tarif, alors pourquoi mettre une entité Tarif ?

2023-05-05 23:26 UTC, jcheron commented on Documents/seance14/acp.md
> +**StatusSos** = (<ins>idStatusSos</ins>, status, #idTarif)
Si on connait l'animal, on connait son statut (sos ou non), mais qu'est ce qui justifie de mettre ce booléen dans une entité ?

2023-05-05 23:26 UTC, jcheron commented on Documents/seance14/acp.md
> +**Adoptant** = (<ins>idAdoptant</ins>, nom, prenom, numAdresse, rue, complement, cp, ville, telFixe, telMobile, email, infoComplementaires, #idAdoption)
Un adoptant ne peut pas faire plusieurs adoptions ?

2023-05-05 23:26 UTC, jcheron commented on Documents/seance14/acp.md
> +**Animal** = (<ins>idAnimal</ins>, dateEntree, espece, nom, sexe, complement, race, dateNaisance, numIdentification, description, compatibilite, #idEspece, #idStatusSos, #idRace, #idAdoptant, #idRefu
Je crois malheureusement qu'un même animal peut être adopté plusieurs fois, si ça se passe mal...

2023-05-05 23:26 UTC, jcheron commented on Documents/seance14/acp.md
> +
Et les horaires du refuge ?

2023-05-05 23:26 UTC, jcheron commented on Documents/seance14/acp.md
> +
Tous les participants à un projet sont des utilisateurs, ayant un login, un password et un nom : l'administrateur qui crée le projet, le scrum master, le product owner, les devs

2023-05-05 23:26 UTC, jcheron commented on Documents/seance14/acp.md
> +
A chaque fois que vous avez une entité avec comme seule propriété l'identifiant, c'est suspect: ProductBacklog, Administrateur, Increment...

Ne paraphrasez pas les règles de gestion, l'expression peut être trompeuse. Poser vous la question : Quelles données doit on mémoriser, et comment ?

2023-05-07 16:01 UTC, scarabe22 commented
Voici mes propositions de correction pour les 3 exercices.
Pas facile de comprendre sans les solutions des séances précédentes.

2023-05-09 01:43 UTC, jcheron commented
> Voici mes propositions de correction pour les 3 exercices. Pas facile de comprendre sans les solutions des séances précédentes.

Oui, je les mets sur Discord

2023-05-11 07:48 UTC, merged