Seance16
scarabe22/nfa085 pull request #12
Opened 2023-05-15 18:42 UTC by scarabe22

Voici ma proposition pour la séance 16.
Je viens de voir que j'aurais pu faire un row reverse pour la firme mais je manque de temps: une autre EU à bosser (NFA071),
exam dans 3 semaines.

2023-05-17 22:08 UTC, jcheron requested changes
Pas mal du tout 😃 
Juste quelques ajustements à effectuer, mentionnés directement dans le code

2023-05-17 22:08 UTC, jcheron commented on docs/assets/css/seance16/exercice-4.css
> +.section-2 {
Pas besoin de créer des classes `section-1`, `section-2` et `section-3` pour gérer l'inversion (imaginez que vous ayez 10 sections...)
Vous pouvez cibler les éléments pairs : 
```css
      section:nth-child(even) {
        flex-direction: row-reverse;
      }
  ```

2023-05-17 22:08 UTC, jcheron commented on docs/assets/images/seance16/section2.png
Les images peuvent être directement requêtées sur **placeholder**
```html
<img src="https://via.placeholder.com/300x200.png?text=Section+2" alt="Section 2" />
```

2023-05-17 22:08 UTC, jcheron commented on docs/js/seance16/exercice-5.js
Je ne sais pas à quoi sert cette modale dans l'exercice 5

2023-05-17 22:08 UTC, jcheron commented on docs/pages/seance16/la-firme.html
> +            <section class="services-mobile">
Il ne faut pas s'autoriser la duplication de contenu, surtout pour obtenir une mise en forme.
C'es le CSS qui doit tout faire.

2023-05-17 22:08 UTC, jcheron commented on docs/pages/seance16/la-firme.html
> +        <div class="container">
La classe `container` devrait permettre de centrer la zone de contenu dans la page, quelque soit la largeur de l'écran: 
- définir un max-width
- mettre margin à auto (left et right) pour centrer

2023-05-17 22:08 UTC, jcheron commented on docs/pages/seance16/la-firme.html
> +            <div class="footer-container">
même problème de centrage avec le `footer-container`

2023-05-18 11:30 UTC, scarabe22 commented on docs/assets/css/seance16/exercice-4.css
> +.section-2 {
vu --> even et odd

2023-05-18 11:32 UTC, scarabe22 commented on docs/assets/images/seance16/section2.png
vu avec https://dummyimage.com

2023-05-18 11:32 UTC, scarabe22 commented on docs/js/seance16/exercice-5.js
exercice-5.js effacé ---> c'était un reliquat de ma tentative avec Semantic UI

2023-05-18 18:28 UTC, scarabe22 commented on docs/pages/seance16/la-firme.html
> +            <section class="services-mobile">
ok avec row-reverse et column-reverse

2023-05-18 21:48 UTC, scarabe22 commented on docs/pages/seance16/la-firme.html
> +        <div class="container">
Est-ce correct maintenant ?

2023-05-22 17:55 UTC, merged