Seance9
scarabe22/nfa085 pull request #7
Opened 2023-04-22 19:06 UTC by scarabe22

Séance ! mergée avec main donc nouveau pull request pour la séance ç

2023-04-23 00:52 UTC, jcheron requested changes
pb sur 
- validation du formulaire (signin)
- présentation (mix de % + position en px)

2023-04-23 00:52 UTC, jcheron commented on docs/js/seance9/signing.js
> +  if (criteriaCount === 0) {
Répétition de if à éviter
Utiliser un array pour ne pas avoir à poser de condition

2023-04-23 00:52 UTC, jcheron commented on docs/js/seance9/signing.js
> +
Toutes ces conditions ne valent que si on a au moins un caractère [a-z] dans le password, en + des autres conditions testées.

2023-04-23 00:52 UTC, jcheron commented on docs/js/seance9/signing.js
> +confirmPasswordInput.addEventListener("input", function () {
Pourquoi mettre un second listener sur le même event de l'élément ?

2023-04-23 00:52 UTC, jcheron commented on docs/pages/seance9/contact.html
> +                        <input type="text" id="firstname" name="firstname" placeholder="Entrez votre prénom" required pattern="[A-Za-z]+">
Et les prénoms composés ?

2023-04-23 00:52 UTC, jcheron commented on docs/pages/seance9/contact.html
> +                        <input type="text" id="lastname" name="lastname" placeholder="Entrez votre nom" required pattern="[A-Za-z]+">
Vous interdisez les particules...

2023-04-23 00:52 UTC, jcheron commented on docs/js/seance9/signing.js
> +
La validation passe même s'il n'y a pas de mot de passe, ou s'il est faible
et aussi si les 2 mots de passe ne sont pas identiques.

2023-04-23 00:52 UTC, jcheron commented on docs/assets/css/seance9/signing.css
> +input[type="email"] {
Pourcentage à éviter, puisque le rendu sera très variable en fonction des écrans:
![image](https://user-images.githubusercontent.com/2511052/233813544-034486b1-5349-4a87-9eb2-a28934babf8d.png)

2023-04-23 09:19 UTC, scarabe22 commented on docs/assets/css/seance9/signing.css
> +input[type="email"] {
Pourcentages remplacés par des px

2023-04-23 22:01 UTC, scarabe22 commented on docs/pages/seance9/contact.html
> +                        <input type="text" id="firstname" name="firstname" placeholder="Entrez votre prénom" required pattern="[A-Za-z]+">
prénoms composés semble ok

2023-04-23 22:01 UTC, scarabe22 commented on docs/pages/seance9/contact.html
> +                        <input type="text" id="lastname" name="lastname" placeholder="Entrez votre nom" required pattern="[A-Za-z]+">
particules semble ok

2023-04-24 09:47 UTC, scarabe22 commented on docs/js/seance9/signing.js
> +  if (criteriaCount === 0) {
array semble ok

2023-04-24 09:47 UTC, scarabe22 commented on docs/js/seance9/signing.js
> +confirmPasswordInput.addEventListener("input", function () {
code inséré dans un seul listener

2023-04-24 09:48 UTC, scarabe22 commented on docs/js/seance9/signing.js
> +
validation rajoutée

2023-04-25 17:32 UTC, merged