add file in correct branch (12 instead of 11)
scarabe22/nfa085 pull request #8
Opened 2023-04-25 17:53 UTC by scarabe22

Voici ma proposition pour un pull request.
Je n'ai toujours pas réussi à changer certaines cardinalités sur looping avec il me semble une entité père avec identifiant et une association binaire ! cf Discord

2023-04-26 00:53 UTC, jcheron requested changes
Sur l'exercice n°3, il faut rechercher des erreurs (Exemple : une CIF avec une propriété, ce qui n'est pas possible), mais il n'est pas question de remettre en cause des règles de gestion que nous n'avons pas.

2023-04-26 00:53 UTC, jcheron commented on Documents/seance12/mea.md
> +La livraison de ces commandes peut se faire selon avec ou sans types de livraison.
Je n'ai pas compris là

2023-04-26 00:53 UTC, jcheron commented on Documents/seance12/mea.md
> +La livraison sans type est identifiée par un numéro unique et une date de livraison.
Il n'y a pas de livraisons sans type

2023-04-26 00:53 UTC, jcheron commented on Documents/seance12/mea.md
> +La livraison peut se faire par lot selon une certaine quantité.
quantité d'articles

2023-04-26 00:53 UTC, jcheron commented on Documents/seance12/mea.md
> +id_TypeLivraison en référence à type de livraison Textuelle "courte":
Textuelle "courte" ?

2023-04-26 00:53 UTC, jcheron commented on Documents/seance12/mea.md
> +Passer(id_commande, id_Client)
` Passer`  ne devient pas une relation, c'est une CIF !

2023-04-26 00:53 UTC, jcheron commented on Documents/seance12/mea.md
> +LivrerEnMode(#id_TypeLivraison, #id_Commande)
Idem, c'est une CIF

2023-04-26 00:53 UTC, jcheron commented on Documents/seance12/mea.md
> +Commande est passée par un et un seul client donc la cardinalité est (1,1)
ok, et que devient ` dateC` , la propriété ?

2023-04-26 00:53 UTC, jcheron commented on Documents/seance12/mea.md
> +Un produit peut être fourni par un ou plusieurs fournisseurs donc la cardinalité entre produit et Fournir est (1,n).
Non, dans les règles de gestion, il est indiqué que le produit est fourni par un fournisseur, pas plusieurs

2023-04-26 00:53 UTC, jcheron commented on Documents/seance12/mea.md
> +
Ce serait un mauvais identifiant (volumineux, et modifiable), le id_fournisseur est mieux

2023-04-26 00:53 UTC, jcheron commented on Documents/seance12/mea.md
> +Un Usager peut souscrire ou pas un seul contrat donc la cardinalité entre Usager et Souscrire est (0,1).
non, pour quelle raison ?

2023-04-26 00:53 UTC, jcheron commented on Documents/seance12/mea.md
> +L'entité DateContrat avec l'attribut dateC n'a pas lieu d'être car on peut mettre dateC en propriété de l'association Souscrire.
Sauf si l'usager peut renouveler son contrat, à des dates différentes.
Ce qui pourrait faire partie des règles de gestion.

2023-04-26 00:53 UTC, jcheron commented on Documents/seance12/mea.md
> +La propriété numImmat de l'association Concerner est superflue.
Superflue, on ne peut le supposer.
mal placée plutôt non ?

2023-04-26 00:53 UTC, jcheron commented on Documents/seance12/mea.md
> +
non, il n'y a pas qu'un seul contrat par modèle de batterie, sinon ça ne serait pas rentable...

2023-05-01 20:05 UTC, merged

2023-05-02 16:19 UTC, scarabe22 commented on Documents/seance12/mea.md
> +La livraison de ces commandes peut se faire selon avec ou sans types de livraison.
moi non plus 🙂

2023-05-02 16:20 UTC, scarabe22 commented on Documents/seance12/mea.md
> +La livraison sans type est identifiée par un numéro unique et une date de livraison.
Ok corrigé. C'était vraiment obscur

2023-05-02 16:20 UTC, scarabe22 commented on Documents/seance12/mea.md
> +La livraison peut se faire par lot selon une certaine quantité.
articles rajouté

2023-05-02 16:21 UTC, scarabe22 commented on Documents/seance12/mea.md
> +id_TypeLivraison en référence à type de livraison Textuelle "courte":
oui c'était dans le cours mais j'enlève ces commentaires

2023-05-02 16:29 UTC, scarabe22 commented on Documents/seance12/mea.md
> +Passer(id_commande, id_Client)
Donc il n'y a rien à préciser quand il s'agit d'un CIF

2023-05-02 16:33 UTC, scarabe22 commented on Documents/seance12/mea.md
> +LivrerEnMode(#id_TypeLivraison, #id_Commande)
De la même façon j'enlève donc `Passer'` et `LivrerEnMode` et `Livrer`

2023-05-02 17:13 UTC, jcheron commented on Documents/seance12/mea.md
> +Passer(id_commande, id_Client)
> Donc il n'y a rien à préciser quand il s'agit d'un CIF au niveau logique MLDR

Si vous avez migration de la clé du père vers le fils, qui devient clé étrangère

2023-05-02 17:35 UTC, scarabe22 commented on Documents/seance12/mea.md
> +Commande est passée par un et un seul client donc la cardinalité est (1,1)
J'ai réussi à créer un MEA avec looping et dateC y figure

2023-05-02 17:35 UTC, scarabe22 commented on Documents/seance12/mea.md
> +Un produit peut être fourni par un ou plusieurs fournisseurs donc la cardinalité entre produit et Fournir est (1,n).
Corrigé

2023-05-02 17:36 UTC, scarabe22 commented on Documents/seance12/mea.md
> +
Je garde id_Fournisseur

2023-05-02 17:49 UTC, scarabe22 commented on Documents/seance12/mea.md
> +
phrase éffacée

2023-05-02 21:23 UTC, scarabe22 commented on Documents/seance12/mea.md
> +Un Usager peut souscrire ou pas un seul contrat donc la cardinalité entre Usager et Souscrire est (0,1).
J'ai complètement remanié l'exo 3 car je pense (au moins) avoir compris ce qui était demandé.